version: '3.0'

expectations:
  population_size: 500

actions:

  generate_study_population_ce1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ce1 --index-date-range "2019-09-01 to 2020-09-01 by month" --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/ce1/input_*.feather

  # generate_study_population_ce2:
  #   run: cohortextractor-v2:latest generate_cohort --cohort-definition analysis/study_definition_ce2.py --output output/ce2/input_cohort.csv #--dummy-data-file analysis/dummy_data.csv
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/ce2/input_cohort.csv

  validate_cohort_v2:
    run: cohortextractor-v2:latest validate_cohort tpp --cohort-definition analysis/study_definition_ce2.py --output output/ce2/generated_sql.csv
    outputs:
      moderately_sensitive:
        cohort: output/ce2/generated_sql.csv

  # generate_report:
  #   run: cohort-report:v2.0.2 output/ce1/input_2019-09-01.feather
  #   needs: [generate_study_population_ce1]
  #   config:
  #     output_path: output/ce1/cohort_reports_outputs
  #   outputs:
  #     moderately_sensitive:
  #       reports: output/ce1/cohort_reports_outputs/*.html
