version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --index-date-range "2019-09-01 to 2020-09-01 by month" #--output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input_*.csv

  generate_report:
    run: cohortreport:v1.0.0 output/input_2019-09-01.csv
    needs: [generate_study_population]
    config:
      variable_types:
          age: int
          sex: categorical
      output_path: output/cohort_reports_outputs
    outputs:
      moderately_sensitive:
        reports: output/cohort_reports_outputs/descriptives_input.html
