version: '3.0'

expectations:
  population_size: 1000

actions:

  generate_study_population_ce1:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_ce1 --index-date-range "2019-09-01 to 2020-09-01 by month" --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/ce1/input_*.feather

  # generate_report:
  #   run: cohort-report:v2.0.2 output/ce1/input_2019-09-01.feather
  #   needs: [generate_study_population_ce1]
  #   config:
  #     output_path: output/ce1/cohort_reports_outputs
  #   outputs:
  #     moderately_sensitive:
  #       reports: output/ce1/cohort_reports_outputs/*.html
